### ISSUE TITLE
Delist: 157.161.57.65

### ISSUE THREAD

**Issue by hb9eue** [certtools/misc#1]
Hi

Your list is from 2016. Yes, I probably had a Tor Exit node running on that IP back then, but noticed quite fast that IP got blocked everywhere. So it's not been active on that IP for long time now.

Please delist!

-Benoît-

**Comment by aaronkaplan** [comment]
Hey Benoit, I delisted this IP however, please note that this list was a folder clearly marked **tests**/. So whoever actually really uses this list from github without checking the official *current* tor exit node list, can't be helped...
I think the bug then actually is with that site using a tests-only list....

But whatever, I removed the IP you mentioned. 
Good luck with finding all the other occurrences on the internet. I image that's pretty time consuming (?).
